using Microsoft.AspNetCore.Mvc;
using MusicGearTracker.Data;


// we need using Models to load the Model(s): Instrument
using MusicGearTracker.Models;

/*
 * In professional MVC applications, 
 * each controller usually manages one domain entity or feature.
 *
 * Example:
 *  - InstrumentsController => manages Instrument entities
 *  - OrdersController => manages Orders
 *  - UsersController => manages Users
 *  - AdminsController => manages Admins
 *
 * The default "HomeController" generated by the project template
 * usually only serves the homepage.
 */
namespace MusicGearTracker.Controllers
{
    public class InstrumentsController : Controller
    {
        /* 
          ASP.NET Core MVC automatically searches for a View 
          that matches the action method name inside a folder
          that matches the controller name.
   
          This follows the design principle: "Convention over Configuration"

          Example:
          Controller: InstrumentsController
          Action: Index()

          MVC will search for the view in the following locations:
          1) Views/Instruments/Index.cshtml
          2) Views/Shared/Index.cshtml

          The first location "1" is the most common place 
          where controller-specific views are stored

          The "Shared" folder "2" is used for views
          that can be reused across multiple controllers

          This behavior is part of the MVC "convention over configuration" design.
          
          If the view is not found in these locations,
          For example, renaming the View folder from "Instruments" to "Devices"
          MVC will:
            > not find the view unless we also rename the controller accordingly
            > throw an InvalidOperationException

          Examples:
          - InstrumentsController.cs => searches for View/Instruments/...
          - DevicesController.cs => searches for View/Devices/...
          - ItemsController.cs => searches for View/Items/...
        */

        /*
         * Injecting the DbContext into InstrumentsController:
         * ***************************************************
         * 
         * After creating and registering our DbContext in Program.cs,
         * we can now use it inside our controllers.
         *
         * ASP.NET Core provides the DbContext instance automatically
         * using the built-in Dependency Injection (DI) system.
         * 
         * We can do it in two steps:
         *
         * Step#1 - Create a private readonly field:
         * ****************************************
         *
         * - The field type is our DbContext class:
         *      MusicGearTrackerDbContext
         *
         * - By convention in C#, private fields often start with "_".
         *
         * - By convention, the DbContext field is commonly named "_context".
         *
         * This field will store the injected DbContext instance 
         * so that we can use it inside our controller methods 
         * to perform database operations (Create, Read, Update, Delete).
         */

        private readonly MusicGearTrackerDbContext _context;

        /*
         * Step#2 - Add the controller constructor:
         * ****************************************
         *
         * The constructor receives the DbContext instance as a parameter.
         *
         * ASP.NET Core automatically creates and passes the DbContext
         * because we previously registered it in Program.cs using:
         *      > builder.Services.AddDbContext<MusicGearTrackerDbContext>();
         *
         * Inside the constructor we assign the injected object
         * to our private field "_context".
         *
         * This allows all action methods in this controller to
         * access the database through Entity Framework Core.
         *
         * Tip :-)
         * The default project template shows a similar example
         * in "HomeController" using "ILogger":
         *
         * public HomeController(ILogger<HomeController> logger)
         * {
         *     _logger = logger;
         * }
         *
         * The concept is the same: 
         * ASP.NET Core injects the required dependency automatically.
         *
         * Link: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection
         */

        /*
         * NOTE ABOUT LOGGER:
         * ******************
         *
         * The default ASP.NET Core MVC template includes a logger (ILogger<T>) in "HomeController"
         * Check the default controller: HomeController.cs
         *
         * Logging is used in real-world applications to:
         *  - Track application behavior
         *  - Record errors and exceptions
         *  - Help with debugging and monitoring
         *
         * Starter Template Example:
         *      private readonly ILogger<HomeController> _logger;
         *
         *      public HomeController(ILogger<HomeController> logger)
         *      {
         *          _logger = logger;
         *      }
         *
         * In this tutorial, we will skip using the logger
         * to keep the focus on:
         *
         *      - ASP.NET Core MVC
         *      - Entity Framework Core
         *      - CRUD operations
         *
         * So we can understand the core concepts 
         * without introducing additional complexity.
         *
         * NOTE:
         * In real-world applications, logging is highly recommended
         * and commonly used in controllers and services.
         * 
         * so for example to combine both properties in the controller constructor:
         *          
         * public InstrumentsController
         *  (ILogger<InstrumentsController> logger, MusicGearTrackerDbContext context)
         *  {
         *      _logger = logger;
         *      _context = context;
         *  }
         *
         * We may work with "logging" in another advanced version of this tutorial in a different repo.
         * 
         * Link: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/
         */

        public InstrumentsController(MusicGearTrackerDbContext context)
        {
            _context = context;
        }

        /*
         * NOTE:
         * *****
         * In ASP.NET Core MVC, each action method typically corresponds
         * to a View with the same name
         *
         * In other words:
         * "Each action method typically returns a View"
         *
         * Example:
         * 1) Action Method => Index()
         * 2) View File => Index.cshtml
         * 3) Location => Views/Instruments/Index.cshtml
         *
         * Because of the MVC conventions, 
         * we do not need to specify the view name explicitly when calling View()
         */
        public IActionResult Index()
        {
            return View();
        }

        /*
           * Adding another action method for demonstration purposes
           * 
           * Instruments() method => Instruments.cshtml view
           * 
           * Again, this follows the MVC "Convention over Configuration" principle :-)
           *
           * MVC will automatically search for the following view:
           *    Views/Instruments/Instruments.cshtml
           *    
           * Link: https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions
        */
        public IActionResult Instruments()
        {
            /*
             * STEP 1: Retrieve all records from the database:
             * ***********************************************
             * 1) Using the "_context" object to access the database
             * 2) Accessing the "Instruments" DbSet (represents our table/collection)
             * 3) Calling the LINQ method "ToList()" to execute the query
             *
             * IMPORTANT NOTE#1:
             * *****************
             * - "ToList()" executes the query and loads the data into memory
             * - The result is stored as a List<Instrument>
             *
             * C# Review: Using "List" and not "Array", why?
             * **********************************************
             * - List<T> is more flexible and commonly used in C#
             * - Supports dynamic sizing and LINQ operations
             *
             * IMPORTANT NOTE#2:
             * *****************
             * As we practiced in JavaScript Framework Code Examples (refer to my and ES6 JSFW repos),
             * in professional applications, we often use the "async" version:
             *
             *      await _context.Instruments.ToListAsync()
             *
             * But for simplicity in this tutorial, we use ToList().
             *
             * Link: https://learn.microsoft.com/en-us/ef/core/querying/
             */

            // ToList() = executes the query + loads data into memory
            var allInstruments = _context.Instruments.ToList();

            /*
             * STEP 2: Pass the data to the View:
             * **********************************
             * - The View receives the data via the "Model"
             * - The model type in the view should be:
             *
             *      @model IEnumerable<Instrument>
             *
             * - "IEnumerable" is preferred over List for flexibility
             *
             * This allows the view to loop through the data and display it.
             */
            return View(allInstruments); // List all instruments with details
        }

        // Adding the action method for Create View:
        /*
            GET: Instruments/Create
            ***********************

            This action method is responsible for displaying the empty form
            used to create/add a new Instrument.

            
            > When a user navigates to:
                
                    /Instruments/Create

            > ASP.NET Core MVC will automatically load the corresponding View:

                    Views/Instruments/Create.cshtml

            This follows the MVC convention: Action Name => View Name

            Link: https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions
        */

        // GET: Instruments/Create => Loading the View for the form
        [HttpGet] // Explicitly specifies GET request (optional, but improves readability and clarity)
        public IActionResult Create()
        {
            return View();
        }

        /*
            POST: Instruments/Create
            ************************
            
            This action method handles the submitted form data.

            1) The form in "Create.cshtml" sends a "POST" request to this action using:

                <form asp-action="Create" method="post">

            2) ASP.NET Core MVC uses "Model Binding" 
            to automatically map the form fields to the "Instrument" object.

            3) After receiving the data:
                - We validate the model
                - Save it to the database
                - Redirect the user to another page

            Link: https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding
        */

        /*
          * Configuring Our Controller to save the Model Information to our Database:
          * *************************************************************************
          * The method:  public IActionResult Create(Instrument instrument)
          *  - for receiving the form submission
          *  - saving the "instrument" object of type "Instrument" that contains all the required values to our database
          * 
          * The "instrument" object is populated automatically via Model Binding, not "Dependency Injection".
         */

        /*
         * IMPORTANT [HttpGet] / [HttpPost] Usage:
         * ***************************************
         * 1) Viewing Data:
         *      > HTTP Method: GET 
         *      > UI Element: <a>
         * 
         * 2) Creating, Editing, or Deleting Data:
         *      > HTTP Method: POST
         *      > UI Element: <form>
         *      
         * - Use a "GET" action with [HttpGet] to display a confirmation page
         * - Use a "POST" action with [HttpPost] to perform the actual deletion/editing/creating operation(s)
         * 
         * This follows the standard ASP.NET Core MVC pattern:
         * GET => [HttpGet] => Display confirmation (Display Edit/Create Form)
         * POST => [HttpPost] => Perform create/edit/delete action
         * 
         * MVC selects actions based on:
         * *****************************
         * > Route
         * > HTTP verb
         */

        /*
         * CRUCIAL SECURITY NOTE: Anti-Forgery Protection:
         * ***********************************************
         * [ValidateAntiForgeryToken] protects against CSRF (Cross-Site Request Forgery) attacks.
         * 
         * It ensures that the POST request comes from a trusted form within this application.
         * 
         * IMPORTANT:
         * - Must be used with @Html.AntiForgeryToken() inside the form
         * - Required for all POST actions that modify data
         * 
         * How to code it:
         * ***************
         * We need to add/use [ValidateAntiForgeryToken] on all "POST" actions:
         * - Create:
         *      [HttpPost]
         *      [ValidateAntiForgeryToken]
         *      public IActionResult Create(Instrument instrument)
         *      
         * - Edit:
         *      [HttpPost]
         *      [ValidateAntiForgeryToken]
         *      public IActionResult Edit(Instrument instrument)
         *      
         * - Delete:
         *      [HttpPost]
         *      [ValidateAntiForgeryToken]
         *      public IActionResult Edit(Instrument instrument)
         *      
         * And also inside the <form> (Refer to the view pages):
         * @Html.AntiForgeryToken()
         * 
         * To summarize:
         * *************
         * > [ValidateAntiForgeryToken] = server-side protection => in controller
         * > @Html.AntiForgeryToken() = client-side token => in form
         * > Used for ALL POST actions
         * > Prevents CSRF attacks
         * 
         * Link: https://cybersecuritynews.com/cross-site-request-forgery/
         * 
         * 
         */

        // POST: Instruments/Create => handling form submission and saving data
        [HttpPost] // Explicitly specifies that this action responds to HTTP POST requests
        [ValidateAntiForgeryToken]
        public IActionResult Create(Instrument instrument)
        {

            /*
             * STEP#1: Validate the incoming model:
             * ************************************
             * The "ModelState.IsValid" checks if the data satisfies
             * validation rules (Data Annotations) defined in the model.
             *
             * If validation fails, we return the same view
             * and display validation errors to the user.
             */
            if (!ModelState.IsValid) // Check if the model is valid based on its annotations
            {
                // The foreach loops is just an extra error validation logic (for us as programmers):
                /*
                foreach (var item in ModelState)
                {
                    foreach (var error in item.Value.Errors)
                    {
                        Console.WriteLine($"Field Value: {item.Key}. Error: {error.ErrorMessage}");
                    }
                }
                */

                // The main required code line:
                return View(instrument); // Return to the view with validation errors
            }
            /*
             * IMPORTANT DEBUG NOTE:
             * *********************
             * If the form submits but no redirect happens,
             * it is often because ModelState.IsValid == false.
             *
             * In this case, the method returns the same view:
             *     return View(instrument);
             *
             * This may appear as if "nothing happened" to the user
             *
             * We need to check "ModelState" errors when debugging form submissions
             */

            /*
             * STEP#2: Add the new entity to the DbContext:
             * ********************************************
             * The DbContext tracks this entity as "Added"
             * but it is NOT yet saved to the database.
             *
             * Template:
             *      _context.TableName.Add(entityObject)
             *      
             * Reminder:
             * In our application:
             *  - Instrument => the entity (model class)
             *  - Instruments => the DbSet property name (represents the table/collection)
             *  
             *  So in our DBContext class file, we put the name to be "Instruments":
             *      public DbSet<Instrument> Instruments { get; set; }
             *  
             *  By default, EF Core will also use "Instruments" 
             *  as the table name in the database (based on conventions).
             */

            _context.Instruments.Add(instrument);

            /*
             * STEP#3: Save changes to the database:
             * *************************************
             * SaveChanges() commits all tracked changes:
             *  - Insert (Add)
             *  - Update
             *  - Delete
             *
             * IMPORTANT:
             * Without calling SaveChanges(), no data will be persisted.
             *
             * Similar concept exists in other technologies like Java and PHP.
             */
            _context.SaveChanges();

            /*
             * STEP#4: Redirect the user after successful submission:
             * ******************************************************
             * We use RedirectToAction to avoid resubmitting the form
             * if the user refreshes the page (Post/Redirect/Get pattern).
             *
             * The user will be redirected to:
             *      InstrumentsController => Instruments()
             *      
             * Tip: Set a breakpoint before the return to test the method (Optional)
             */
            return RedirectToAction("Instruments");
        }

        /*
         * Using "int?" (nullable int) for the id instead of just "int":
         * *************************************************************
         *
         * Remember that the "id" comes from the URL:
         *     /Instruments/Edit/7
         *
         * However, a user could manually navigate to:
         *     /Instruments/Edit
         *
         * In that case, no id is provided, so:
         *     id = null
         *
         * Using "int?" allows us to safely check:
         *
         *     if (id == null)
         *
         * and return an appropriate response, for example: "NotFound".
         *
         * This is a "Defensive Programming" practice used in real-world applications
         * to handle invalid or missing input safely.
         * 
         * Even though our UI always sends a valid "id",
         * users can manually modify URLs or send bad requests.
         * 
         * Therefore, we validate: if (id == null)
         * to prevent errors.
         * 
         * This is a common best practice in ASP.NET Core MVC and general software engineering.
         * 
         * Link: https://en.wikipedia.org/wiki/Defensive_programming
         * Link: https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions
         */
        [HttpGet] // GET (Just loading form for editing the current instrument - No Edit Action)
        public IActionResult Edit(int? id)
        {
            // For a "Professional Defensive Pattern", adding the following two if statements:
            if (id == null)
            {
                return NotFound(); // or BadRequest()
            }

            var instrument = _context.Instruments.Find(id);

            if (instrument == null)
            {
                return NotFound();
            }

            // Finally, return the view simply and passing the current found instrument
            return View(instrument);
        }

        [HttpPost] // POST (save changes on the current instrument - Edit Action)
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Instrument instrument)
        {
            // TIP: Following the same logic as with "Create", just using "Update" method instead of "Add" :-)
            // Finally, return the view simply and passing the current found instrument
            /*
            * STEP#1: Validate the incoming model:
            */
            if (!ModelState.IsValid) // Check if the model is valid based on its annotations
            {
                // The main required code line:
                return View(instrument); // Return to the view with validation errors
            }
            /*
             * STEP#2: Update the current entity in the DbContext:
             * ***************************************************
             * The DbContext tracks this entity as "Updated"
             * but it is NOT yet saved to the database.
             *
             * Template:
             *      _context.TableName.Update(entityObject)
             */

            _context.Instruments.Update(instrument);

            /*
             * STEP#3: Save changes to the database:
             */
            _context.SaveChanges();

            /*
             * STEP#4: Redirect the user after successful submission to avoid form resubmission:
             */
            return RedirectToAction("Instruments");
        }

        /*
         * IMPORTANT NOTE:
         * ***************
         * As learned in Java Programming Course:
         * 
         * In object-oriented programming, method overloading means:
         *      Multiple methods have the same name but different parameters.
         * 
         * Although, in our above example of using two method with same name "Create" but different parameters,
         * but the real selector is the HTTP method (GET vs POST), not just the parameters.
         * 
         * What Happens in ASP.NET Core MVC?
         * *********************************
         * 
         * MVC decides which one runs based on the HTTP request type:
         * - If "Request" => GET => Then => "Method Used" => Create()  
         * - If "Request" => POST => Then =>"Method Used" => Create(Instrument instrument) 
         * 
         * So MVC chooses the action based on HTTP verb attributes like:
         * [HttpGet]
         * [HttpPost]
         * 
         * The framework routing system examines:
         * **************************************
         * 1) Controller name
         * 2) Action name
         * 3) HTTP verb
         * Then it selects the correct method.
         * 
         * So MVC will look for:
         * [HttpPost]
         * Create(...)
         * 
         * In other words,
         * ASP.NET Core MVC allows multiple action methods
         * to have the same name (Create in our example).
         * 
         * One action displays the form (GET request),
         * while the other processes the submitted form (POST request).
         * 
         * NOTE: MVC determines which action to execute based on the "HTTP method".
         * 
         * Although this looks similar to method overloading in OOP,
         * the action is actually selected using HTTP verb attributes such as [HttpGet] and [HttpPost].
         * 
         * Link: https://learn.microsoft.com/aspnet/core/mvc/controllers/actions
         */

        /*
         * Using "int?" for Delete => public IActionResult Delete(int? id):
         * ****************************************************************
         * Even though "Delete" operations require a valid ID,
         * the ID value comes from the URL as with "Edit" operation.
         *
         * A user can manually navigate to:
         *     /Instruments/Delete
         *
         * In this case:
         *     id = null
         *
         * Therefore, we must use "int?" (nullable int)
         * to safely handle missing or invalid input.
         *
         * This is part of "Defensive Programming",
         * which is a standard practice in real-world applications.
         *
         * Link: https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/actions
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int? id)
        {
            // STEP#1: Validating the incoming id
            if (id == null)
            {
                // Returns a 404 status code:
                return NotFound();
                /*
                 * A 404 status code is returned 
                 * when the product represented by id doesn't exist in the underlying data store.
                 * The NotFound convenience method is invoked as shorthand for return new NotFoundResult();
                 * 
                 * link: https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-10.0#synchronous-action
                 * link: https://learn.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-10.0#iactionresult-type
                 */
            }

            // STEP#2: Find the entity (searching for the entity's id in our database)
            /*
             * Using EF Core built-in method "Find()" for primary keys
             * Find() for primary keys
             * 
             * In this case, we are searching by the primary key (Id).
             *
             * Entity Framework Core provides a built-in method:
             *
             *      Find(id)
             *      
             * which is optimized specifically for primary key lookups
             *    
             * Using Find(id):
             * ***************
             * - Simpler and more readable
             * - Faster (uses EF Core tracking cache if available)
             * - Designed specifically for primary keys
             * 
             * 
             * Using SingleOrDefault():
             * ************************
             * - ONLY when searching by non-primary key
             * - Still working fine in our case below but NOT recommended
             * - Using LINQ like:
             *
             *      SingleOrDefault(x => x.Id == id)
             *      
             * Example:
             * _context.Instruments.SingleOrDefault(x => x.Name == "Piano");
             *
             * is more generic and typically used for non-primary key queries.
             * 
             * Therefore, Find() is the recommended and more professional approach here.
             *      
             * Link: https://learn.microsoft.com/en-us/ef/core/querying/
             */
            var instrument = _context.Instruments.Find(id);

            if (instrument == null)
            {
                return NotFound();
            }

            // STEP#3: Remove the entity (as we are using Entity Framework)
            _context.Instruments.Remove(instrument);

            // STEP#4: Save changes after finishing our modification
            _context.SaveChanges();

            // STEP#5: Redirect back to another view => All Instruments View "Instruments.cshtml"
            return RedirectToAction("Instruments");
        }
    }
}
